name: CI-CD

on:
  push:
    branches: ["main"]
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v3.1.0
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: ./src/
        file: ./src/Dockerfile
        push: true
        tags: |
          MrNiero/kube-news-v1
          MrNiero/kube-news-latest
        
        
