name: CI-CD

on:
  push:
    branches: ["main"]
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v3.1.0

    - name: Docker Authentication
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: ./src/
        file: ./src/Dockerfile
        push: false
        
    - name: "Docker build image with version tag"
      run: |
        make image IMAGE_TAG=${{ github.event.release.tag_name }}
        make image IMAGE_TAG=latest
     - name: "Push to container registry"
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REG -u $GITHUB_ACTOR --password-stdin
        make push IMAGE_TAG=${{ github.event.release.tag_name }}
        make push IMAGE_TAG=latest

